# Generated by Django 5.2 on 2025-04-22 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='content',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='heart_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
