# Generated by Django 5.2 on 2025-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('radiology', 'Radiology'), ('pathology', 'Pathology')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('EMERGENCY', 'Emergency Services'), ('DEPARTMENT', 'Department')], max_length=20),
        ),
    ]
