# Generated by Django 5.2 on 2025-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='order_type',
            field=models.CharField(choices=[('ct_scan', 'CT Scan'), ('pet_scan', 'PET Scan'), ('x_ray', 'X-Ray'), ('blood_test', 'Blood Test')], max_length=50),
        ),
    ]
