# Generated by Django 5.2 on 2025-04-27 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medicaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('vitals', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(limit_choices_to={'role': 'EMERGENCY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
